#Makefile

all: server

client: client.c
	gcc -Wall client.c -o client

example: example.c
	gcc -Wall example.c -o example

server: server.c
	gcc -Wall server.c -o server

clean: 
	rm -f client server
